# Makefile.in generated by automake 1.11.2 from Makefile.am.
# src/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/POC_0528
pkgincludedir = $(includedir)/POC_0528
pkglibdir = $(libdir)/POC_0528
pkglibexecdir = $(libexecdir)/POC_0528
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = arm-bluegiga-linux-gnueabi
bin_PROGRAMS = POC_0528$(EXEEXT)
subdir = src
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_POC_0528_OBJECTS = POC_0528-POC_0528.$(OBJEXT) \
	POC_0528-rsi.$(OBJEXT) POC_0528-rsi_commands.$(OBJEXT) \
	POC_0528-serial.$(OBJEXT) POC_0528-gpio.$(OBJEXT) \
	POC_0528-crc.$(OBJEXT) POC_0528-misc.$(OBJEXT) \
	POC_0528-led.$(OBJEXT)
POC_0528_OBJECTS = $(am_POC_0528_OBJECTS)
POC_0528_LDADD = $(LDADD)
POC_0528_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(POC_0528_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(POC_0528_SOURCES)
DIST_SOURCES = $(POC_0528_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/har/workspace/POC_0528/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/har/workspace/POC_0528/missing --run tar
AR = arm-bluegiga-linux-gnueabi-ar
AUTOCONF = ${SHELL} /home/har/workspace/POC_0528/missing --run autoconf
AUTOHEADER = ${SHELL} /home/har/workspace/POC_0528/missing --run autoheader
AUTOMAKE = ${SHELL} /home/har/workspace/POC_0528/missing --run automake-1.11
AWK = gawk
CC = arm-bluegiga-linux-gnueabi-gcc
CCDEPMODE = depmode=gcc3
CFLAGS =  -g -O0  -march=armv5te  -marm -mthumb-interwork  -mtune=arm926ej-s --sysroot=/home/har/KST/Allegion/bluegiga-sdk/build/tmp/sysroots/apx4devkit
CPP = arm-bluegiga-linux-gnueabi-gcc -E
CPPFLAGS =  -march=armv5te  -marm -mthumb-interwork  -mtune=arm926ej-s --sysroot=/home/har/KST/Allegion/bluegiga-sdk/build/tmp/sysroots/apx4devkit
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /home/har/KST/Allegion/bluegiga-sdk/build/tmp/sysroots/i686-linux/usr/libexec/armv5te-bluegiga-linux-gnueabi/gcc/arm-bluegiga-linux-gnueabi/4.6.4/ld
LDFLAGS =  --sysroot=/home/har/KST/Allegion/bluegiga-sdk/build/tmp/sysroots/apx4devkit
LIBOBJS = 
LIBS = 
LIBTOOL = $(top_builddir)/arm-bluegiga-linux-gnueabi-libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/har/workspace/POC_0528/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /home/har/KST/Allegion/bluegiga-sdk/build/tmp/sysroots/i686-linux/usr/bin/armv5te-bluegiga-linux-gnueabi/arm-bluegiga-linux-gnueabi-nm -B
NMEDIT = 
OBJDUMP = arm-bluegiga-linux-gnueabi-objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = POC_0528
PACKAGE_BUGREPORT = 
PACKAGE_NAME = POC_0528
PACKAGE_STRING = POC_0528 0.1.0
PACKAGE_TARNAME = poc_0528
PACKAGE_URL = 
PACKAGE_VERSION = 0.1.0
PATH_SEPARATOR = :
POC_0528_CFLAGS = 
POC_0528_LIBS = 
RANLIB = arm-bluegiga-linux-gnueabi-ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = arm-bluegiga-linux-gnueabi-strip
VERSION = 0.1.0
abs_builddir = /home/har/workspace/POC_0528/src
abs_srcdir = /home/har/workspace/POC_0528/src
abs_top_builddir = /home/har/workspace/POC_0528
abs_top_srcdir = /home/har/workspace/POC_0528
ac_ct_AR = 
ac_ct_CC = 
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-linux
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = arm-bluegiga-linux-gnueabi
host_alias = arm-bluegiga-linux-gnueabi
host_cpu = arm
host_os = linux-gnueabi
host_vendor = bluegiga
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/har/workspace/POC_0528/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = arm-bluegiga-linux-gnueabi
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
POC_0528_SOURCES = POC_0528.c rsi.c rsi_commands.c serial.c gpio.c crc.c misc.c led.c
AM_CFLAGS = 
AM_LDFLAGS = 
CLEANFILES = *~ 
all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu src/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu src/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
POC_0528$(EXEEXT): $(POC_0528_OBJECTS) $(POC_0528_DEPENDENCIES) 
	@rm -f POC_0528$(EXEEXT)
	$(POC_0528_LINK) $(POC_0528_OBJECTS) $(POC_0528_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/POC_0528-POC_0528.Po
include ./$(DEPDIR)/POC_0528-crc.Po
include ./$(DEPDIR)/POC_0528-gpio.Po
include ./$(DEPDIR)/POC_0528-led.Po
include ./$(DEPDIR)/POC_0528-misc.Po
include ./$(DEPDIR)/POC_0528-rsi.Po
include ./$(DEPDIR)/POC_0528-rsi_commands.Po
include ./$(DEPDIR)/POC_0528-serial.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

POC_0528-POC_0528.o: POC_0528.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-POC_0528.o -MD -MP -MF $(DEPDIR)/POC_0528-POC_0528.Tpo -c -o POC_0528-POC_0528.o `test -f 'POC_0528.c' || echo '$(srcdir)/'`POC_0528.c
	$(am__mv) $(DEPDIR)/POC_0528-POC_0528.Tpo $(DEPDIR)/POC_0528-POC_0528.Po
#	source='POC_0528.c' object='POC_0528-POC_0528.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-POC_0528.o `test -f 'POC_0528.c' || echo '$(srcdir)/'`POC_0528.c

POC_0528-POC_0528.obj: POC_0528.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-POC_0528.obj -MD -MP -MF $(DEPDIR)/POC_0528-POC_0528.Tpo -c -o POC_0528-POC_0528.obj `if test -f 'POC_0528.c'; then $(CYGPATH_W) 'POC_0528.c'; else $(CYGPATH_W) '$(srcdir)/POC_0528.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-POC_0528.Tpo $(DEPDIR)/POC_0528-POC_0528.Po
#	source='POC_0528.c' object='POC_0528-POC_0528.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-POC_0528.obj `if test -f 'POC_0528.c'; then $(CYGPATH_W) 'POC_0528.c'; else $(CYGPATH_W) '$(srcdir)/POC_0528.c'; fi`

POC_0528-rsi.o: rsi.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-rsi.o -MD -MP -MF $(DEPDIR)/POC_0528-rsi.Tpo -c -o POC_0528-rsi.o `test -f 'rsi.c' || echo '$(srcdir)/'`rsi.c
	$(am__mv) $(DEPDIR)/POC_0528-rsi.Tpo $(DEPDIR)/POC_0528-rsi.Po
#	source='rsi.c' object='POC_0528-rsi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-rsi.o `test -f 'rsi.c' || echo '$(srcdir)/'`rsi.c

POC_0528-rsi.obj: rsi.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-rsi.obj -MD -MP -MF $(DEPDIR)/POC_0528-rsi.Tpo -c -o POC_0528-rsi.obj `if test -f 'rsi.c'; then $(CYGPATH_W) 'rsi.c'; else $(CYGPATH_W) '$(srcdir)/rsi.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-rsi.Tpo $(DEPDIR)/POC_0528-rsi.Po
#	source='rsi.c' object='POC_0528-rsi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-rsi.obj `if test -f 'rsi.c'; then $(CYGPATH_W) 'rsi.c'; else $(CYGPATH_W) '$(srcdir)/rsi.c'; fi`

POC_0528-rsi_commands.o: rsi_commands.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-rsi_commands.o -MD -MP -MF $(DEPDIR)/POC_0528-rsi_commands.Tpo -c -o POC_0528-rsi_commands.o `test -f 'rsi_commands.c' || echo '$(srcdir)/'`rsi_commands.c
	$(am__mv) $(DEPDIR)/POC_0528-rsi_commands.Tpo $(DEPDIR)/POC_0528-rsi_commands.Po
#	source='rsi_commands.c' object='POC_0528-rsi_commands.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-rsi_commands.o `test -f 'rsi_commands.c' || echo '$(srcdir)/'`rsi_commands.c

POC_0528-rsi_commands.obj: rsi_commands.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-rsi_commands.obj -MD -MP -MF $(DEPDIR)/POC_0528-rsi_commands.Tpo -c -o POC_0528-rsi_commands.obj `if test -f 'rsi_commands.c'; then $(CYGPATH_W) 'rsi_commands.c'; else $(CYGPATH_W) '$(srcdir)/rsi_commands.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-rsi_commands.Tpo $(DEPDIR)/POC_0528-rsi_commands.Po
#	source='rsi_commands.c' object='POC_0528-rsi_commands.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-rsi_commands.obj `if test -f 'rsi_commands.c'; then $(CYGPATH_W) 'rsi_commands.c'; else $(CYGPATH_W) '$(srcdir)/rsi_commands.c'; fi`

POC_0528-serial.o: serial.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-serial.o -MD -MP -MF $(DEPDIR)/POC_0528-serial.Tpo -c -o POC_0528-serial.o `test -f 'serial.c' || echo '$(srcdir)/'`serial.c
	$(am__mv) $(DEPDIR)/POC_0528-serial.Tpo $(DEPDIR)/POC_0528-serial.Po
#	source='serial.c' object='POC_0528-serial.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-serial.o `test -f 'serial.c' || echo '$(srcdir)/'`serial.c

POC_0528-serial.obj: serial.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-serial.obj -MD -MP -MF $(DEPDIR)/POC_0528-serial.Tpo -c -o POC_0528-serial.obj `if test -f 'serial.c'; then $(CYGPATH_W) 'serial.c'; else $(CYGPATH_W) '$(srcdir)/serial.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-serial.Tpo $(DEPDIR)/POC_0528-serial.Po
#	source='serial.c' object='POC_0528-serial.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-serial.obj `if test -f 'serial.c'; then $(CYGPATH_W) 'serial.c'; else $(CYGPATH_W) '$(srcdir)/serial.c'; fi`

POC_0528-gpio.o: gpio.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-gpio.o -MD -MP -MF $(DEPDIR)/POC_0528-gpio.Tpo -c -o POC_0528-gpio.o `test -f 'gpio.c' || echo '$(srcdir)/'`gpio.c
	$(am__mv) $(DEPDIR)/POC_0528-gpio.Tpo $(DEPDIR)/POC_0528-gpio.Po
#	source='gpio.c' object='POC_0528-gpio.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-gpio.o `test -f 'gpio.c' || echo '$(srcdir)/'`gpio.c

POC_0528-gpio.obj: gpio.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-gpio.obj -MD -MP -MF $(DEPDIR)/POC_0528-gpio.Tpo -c -o POC_0528-gpio.obj `if test -f 'gpio.c'; then $(CYGPATH_W) 'gpio.c'; else $(CYGPATH_W) '$(srcdir)/gpio.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-gpio.Tpo $(DEPDIR)/POC_0528-gpio.Po
#	source='gpio.c' object='POC_0528-gpio.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-gpio.obj `if test -f 'gpio.c'; then $(CYGPATH_W) 'gpio.c'; else $(CYGPATH_W) '$(srcdir)/gpio.c'; fi`

POC_0528-crc.o: crc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-crc.o -MD -MP -MF $(DEPDIR)/POC_0528-crc.Tpo -c -o POC_0528-crc.o `test -f 'crc.c' || echo '$(srcdir)/'`crc.c
	$(am__mv) $(DEPDIR)/POC_0528-crc.Tpo $(DEPDIR)/POC_0528-crc.Po
#	source='crc.c' object='POC_0528-crc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-crc.o `test -f 'crc.c' || echo '$(srcdir)/'`crc.c

POC_0528-crc.obj: crc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-crc.obj -MD -MP -MF $(DEPDIR)/POC_0528-crc.Tpo -c -o POC_0528-crc.obj `if test -f 'crc.c'; then $(CYGPATH_W) 'crc.c'; else $(CYGPATH_W) '$(srcdir)/crc.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-crc.Tpo $(DEPDIR)/POC_0528-crc.Po
#	source='crc.c' object='POC_0528-crc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-crc.obj `if test -f 'crc.c'; then $(CYGPATH_W) 'crc.c'; else $(CYGPATH_W) '$(srcdir)/crc.c'; fi`

POC_0528-misc.o: misc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-misc.o -MD -MP -MF $(DEPDIR)/POC_0528-misc.Tpo -c -o POC_0528-misc.o `test -f 'misc.c' || echo '$(srcdir)/'`misc.c
	$(am__mv) $(DEPDIR)/POC_0528-misc.Tpo $(DEPDIR)/POC_0528-misc.Po
#	source='misc.c' object='POC_0528-misc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-misc.o `test -f 'misc.c' || echo '$(srcdir)/'`misc.c

POC_0528-misc.obj: misc.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-misc.obj -MD -MP -MF $(DEPDIR)/POC_0528-misc.Tpo -c -o POC_0528-misc.obj `if test -f 'misc.c'; then $(CYGPATH_W) 'misc.c'; else $(CYGPATH_W) '$(srcdir)/misc.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-misc.Tpo $(DEPDIR)/POC_0528-misc.Po
#	source='misc.c' object='POC_0528-misc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-misc.obj `if test -f 'misc.c'; then $(CYGPATH_W) 'misc.c'; else $(CYGPATH_W) '$(srcdir)/misc.c'; fi`

POC_0528-led.o: led.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-led.o -MD -MP -MF $(DEPDIR)/POC_0528-led.Tpo -c -o POC_0528-led.o `test -f 'led.c' || echo '$(srcdir)/'`led.c
	$(am__mv) $(DEPDIR)/POC_0528-led.Tpo $(DEPDIR)/POC_0528-led.Po
#	source='led.c' object='POC_0528-led.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-led.o `test -f 'led.c' || echo '$(srcdir)/'`led.c

POC_0528-led.obj: led.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -MT POC_0528-led.obj -MD -MP -MF $(DEPDIR)/POC_0528-led.Tpo -c -o POC_0528-led.obj `if test -f 'led.c'; then $(CYGPATH_W) 'led.c'; else $(CYGPATH_W) '$(srcdir)/led.c'; fi`
	$(am__mv) $(DEPDIR)/POC_0528-led.Tpo $(DEPDIR)/POC_0528-led.Po
#	source='led.c' object='POC_0528-led.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(POC_0528_CFLAGS) $(CFLAGS) -c -o POC_0528-led.obj `if test -f 'led.c'; then $(CYGPATH_W) 'led.c'; else $(CYGPATH_W) '$(srcdir)/led.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool ctags distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
